# github action workflow that publishes docker image that is a python file to github package registry 

name: Publish Docker image to GitHub Container Registry
# trigger when pushed on main branch

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v1
        with:
          name: blackgirlbytes/docker-image-tweet/example-copilot
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          registry: docker.pkg.github.com
          tag_with_ref: true
          tag_with_sha: true



