# github action workflow that publishes docker image that is a python file to github package registry 

name: Publish Docker image to GitHub Container Registry
# trigger when pushed on main branch

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          registry: ghcr.io
      - name: Build and push
        run: |
              docker build . --tag ghcr.io/blackgirlbytes/hello-docker-gcr-demo:latest
              docker run ghcr.io/blackgirlbytes/hello-docker-gcr-demo:latest
              docker push ghcr.io/blackgirlbytes/hello-docker-gcr-demo:latest


